[Log]
Level = "info"
Environment = "production"
Outputs = ["stderr"]

[SyncDB]
Database = "postgres"
User = "bridge_user"
Name = "bridge_db"
Password = "aXPqaRvgo5DfnTbHtpYS9rMhVpjvb6tY"
Host = "bridge-db-001"
Port = "5432"
MaxConns = 20

[Etherman]
l1URL = "https://eth-sepolia.g.alchemy.com/v2/Y-mJROfy_tuFD3B75v3v3OMy2rwqxKrI"
L2URLs = ["http://zkevm-node-rpc-001:8123"]

[Synchronizer]
SyncInterval = "5s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"
    # Read only
    [BridgeServer.DB]
    Database = "postgres"
    User = "bridge_user"
    Name = "bridge_db"
    Password = "aXPqaRvgo5DfnTbHtpYS9rMhVpjvb6tY"
    Host = "bridge-db-001"
    Port = "5432"
    MaxConns = 20

[NetworkConfig]
GenBlockNumber = "5825309"
PolygonBridgeAddress = "0x31Ed1657B6f4Bf5eBC6b5cBc8818ecbAbB5Bda68"
PolygonZkEVMGlobalExitRootAddress = "0x5f7430F42257B11032Cc6EBBDA4574ecD25E502a"
PolygonRollupManagerAddress = "0x2885c9626394768212c8ba48dCC410786Dd19593"
PolygonZkEVMAddress = "0x5B1C462ec4D9448cE78904d0CC7A7C631c412035"
L2PolygonBridgeAddresses = ["0x31Ed1657B6f4Bf5eBC6b5cBc8818ecbAbB5Bda68"]

[ClaimTxManager]
FrequencyToMonitorTxs = "5s"
PrivateKey = {Path = "/etc/zkevm/claimtxmanager.keystore", Password = "pSnv6Dh5s9ahuzGzH9RoCDrKAMddaX3m"}
Enabled = true
RetryInterval = "1s"
RetryNumber = 10